#!/usr/local/bin/lua

-- Snarwin is a Kux hyperLKernel

local snarboot = require "kernel.boot"

snarboot.order:create_boot(0x02, "Test OS", function()
    print("test boot")
end)

print(snarboot.order.boot_table[2].init())